### ISSUE TITLE
离线签名解决方法

### ISSUE THREAD

**Issue by jlinzhou** [myxtype/filecoin-client#3]
我是把签名的代码单独拿出来，"github.com/ipsn/go-secp256k1"换成了以太坊的"github.com/ethereum/go-ethereum/crypto/secp256k1"就可以了
`package util

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"fmt"
	"github.com/filecoin-project/go-address"
	"github.com/ethereum/go-ethereum/crypto/secp256k1"
	"github.com/minio/blake2b-simd"
)

const PrivateKeyBytes = 32

type secpSigner struct{}

func (secpSigner) GenPrivate() ([]byte, error) {
	key, err := ecdsa.GenerateKey(secp256k1.S256(), rand.Reader)
	if err != nil {
		return nil, err
	}
	privkey := make([]byte, PrivateKeyBytes)
	blob := key.D.Bytes()
	copy(privkey[PrivateKeyBytes-len(blob):], blob)
	return privkey, nil
}

func (secpSigner) ToPublic(pk []byte) ([]byte, error) {
	x, y := secp256k1.S256().ScalarBaseMult(pk)
	return elliptic.Marshal(secp256k1.S256(), x, y), nil
}

func (secpSigner) Sign(pk []byte, msg []byte) ([]byte, error) {
	b2sum := blake2b.Sum256(msg)
	sig, err := secp256k1.Sign(b2sum[:], pk)
	if err != nil {
		return nil, err
	}
	return sig, nil
}

func (secpSigner) Verify(sig []byte, a address.Address, msg []byte) error {
	b2sum := blake2b.Sum256(msg)
	pubk, err := secp256k1.RecoverPubkey(b2sum[:], sig)
	if err != nil {
		return err
	}
	maybeaddr, err := address.NewSecp256k1Address(pubk)
	if err != nil {
		return err
	}
	if a != maybeaddr {
		return fmt.Errorf("signature did not match")
	}
	return nil
}`

**Comment by myxtype** [comment]
我之前也这样做过，但是他们都是使用的同一个库，好像不行，但我会重新试一下。

**Comment by myxtype** [comment]
刚刚重新试了一下，还是不行，问一下你的系统是不是Windows @jlinzhou

**Comment by jlinzhou** [comment]
> 刚刚重新试了一下，还是不行，问一下你的系统是不是Windows @jlinzhou

mac和linux都可以

**Comment by myxtype** [comment]
已在 #4 解决。
