### ISSUE TITLE
Cid 问题。

### ISSUE THREAD

**Issue by Gui1105** [myxtype/filecoin-client#6]
messageId := "bafy2bzacec6rz3qox7ggeataldk6nsmg5rtq2xusyqwqd24mdc5cao3lnsfos"
id, err := cid.Parse(messageId)
// id = bafy2bzacec6rz3qox7ggeataldk6nsmg5rtq2xusyqwqd24mdc5cao3lnsfos
// id = messageId

message, err := client.ChainGetMessage(context.Background(), id)
newId = message.Cid().String()
// newId = bafy2bzaceaaeakuwwgbistlzc5ih7ioxqu4q4qok4cvzozxuvzbp3wsxp3ios
// newId != messageId

你好，通过 client.ChainGetMessage() 方法获取message，message得到的Cid不一致。求解答。

**Comment by Gui1105** [comment]
如果传的 messageId是“bafy2bzaceaaeakuwwgbistlzc5ih7ioxqu4q4qok4cvzozxuvzbp3wsxp3ios”，则cid一致。

**Comment by myxtype** [comment]
我有点忘记了，好像是MpoolPush返回的cid是SignedMessage的cid（区块链浏览器上显示的cid），Message的cid是另一个不同的。

**Comment by myxtype** [comment]
因为用不到SignedMessage的cid，所以这个SignedMessage的Cid方法我就没写，如果是实在要用的话，我可以晚点改一下。

**Comment by myxtype** [comment]
如果是遍历区块，充值业务的话，可以参考：
https://github.com/myxtype/filecoin-client/issues/1#issuecomment-716393563

**Comment by Gui1105** [comment]
> 如果是遍历区块，充值业务的话，可以参考：
> [#1 (comment)](https://github.com/myxtype/filecoin-client/issues/1#issuecomment-716393563)

对的，就是浏览器查不到cid的问题，非常感谢！

对了，转账交易我是在SecpkMessages里面找到的，BlsMessages里面没有。

**Comment by Gui1105** [comment]
> 如果是遍历区块，充值业务的话，可以参考：
> [#1 (comment)](https://github.com/myxtype/filecoin-client/issues/1#issuecomment-716393563)

下面的是我写的方法（根据高度查询所有交易），现在的问题就是这个CID不是我想要的，在浏览器中查不到。
```

// GetMessagesByHeight - 根据高度查询所有交易
func (f FileCoin) GetMessagesByHeight(height int64) (messages []*types.Message, err error) {

	ts, err := client.ChainGetTipSetByHeight(context.Background(), height, nil)
	if err != nil {
		return
	}

	var result []*types.Message
	for _, n := range ts.Cids {
		bm, err := client.ChainGetBlockMessages(context.Background(), n)
		if err != nil {
			continue
		}
		for _, m := range bm.SecpkMessages {
			result = append(result, m.Message)
		}
		result = append(result, bm.BlsMessages...)
	}

        // 去重
	m := map[string]*types.Message{}
	for _, message := range result {
		if id := message.Cid().String(); m[id] == nil {
			m[id] = message
		}
	}

	for _, message := range m {
		messages = append(messages, message)
	}

	return
}

```

**Comment by myxtype** [comment]
我稍后改一下，这个是有点问题。

**Comment by Gui1105** [comment]
> 我稍后改一下，这个是有点问题。

大佬给力！！

我还写了个转账的接口，
接口返回正常（“bafy2bzaceb2wzgi3sn3qv3tvy73rvbcrolcjrkjb67igbkxkztifxqdtm7g52”），
这个CID浏览器查不到，并且转账账户也没有转账记录。

不知道是什么问题？

**Comment by myxtype** [comment]
更新了哈，充值流程参见：/examples/recharge

**Comment by Gui1105** [comment]
> 更新了哈，充值流程参见：/examples/recharge

大佬给力，灰常感谢！[抱拳][抱拳]
