### ISSUE TITLE
转账时，Nonce值的问题。

### ISSUE THREAD

**Issue by Gui1105** [myxtype/filecoin-client#7]
` StateGetActor() `方法放回的是账户当前的Nonce值，如果账户当前有N个Pending的交易，那这个Nonce值要赋值什么？

```

	actor, err := c.StateGetActor(context.Background(), msg.From, nil)
	if err != nil {
		t.Error(err)
	}

	msg.Nonce = actor.Nonce

```

**Comment by Gui1105** [comment]
大佬，我又来了。 [捂脸]

**Comment by Gui1105** [comment]
我看到[api文档](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#MpoolGetNonce)，有个 ` Filecoin.MpoolGetNonce `，这个可用吗？

```

// GetNonce - 获取指定发送账号的下一个nonce值
func (f *FileCoin) GetNonce(ctx context.Context, address string) (nonce uint64, err error) {
	return nonce, client.Request(ctx, client.FilecoinMethod("MpoolGetNonce"), nonce, address)
}

```

**Comment by myxtype** [comment]
> 我看到[api文档](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#MpoolGetNonce)，有个 `Filecoin.MpoolGetNonce`，这个可用吗？
> 
> ```
> 
> // GetNonce - 获取指定发送账号的下一个nonce值
> func (f *FileCoin) GetNonce(ctx context.Context, address string) (nonce uint64, err error) {
> 	return nonce, client.Request(ctx, client.FilecoinMethod("MpoolGetNonce"), nonce, address)
> }
> ```

这个不太清楚，我在最新的版本里增加了这个方法。

**Comment by Gui1105** [comment]
> > 我看到[api文档](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#MpoolGetNonce)，有个 `Filecoin.MpoolGetNonce`，这个可用吗？
> > ```
> > 
> > // GetNonce - 获取指定发送账号的下一个nonce值
> > func (f *FileCoin) GetNonce(ctx context.Context, address string) (nonce uint64, err error) {
> > 	return nonce, client.Request(ctx, client.FilecoinMethod("MpoolGetNonce"), nonce, address)
> > }
> > ```
> 
> 这个不太清楚，我在最新的版本里增加了这个方法。

新增的方法，好像不太行，返回错误。。

**Comment by myxtype** [comment]
> > > 我看到[api文档](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#MpoolGetNonce)，有个 `Filecoin.MpoolGetNonce`，这个可用吗？
> > > ```
> > > 
> > > // GetNonce - 获取指定发送账号的下一个nonce值
> > > func (f *FileCoin) GetNonce(ctx context.Context, address string) (nonce uint64, err error) {
> > > 	return nonce, client.Request(ctx, client.FilecoinMethod("MpoolGetNonce"), nonce, address)
> > > }
> > > ```
> > 
> > 
> > 这个不太清楚，我在最新的版本里增加了这个方法。
> 
> 新增的方法，好像不太行，返回错误。。

我这里测试没问题，你报错具体提示什么？

**Comment by Gui1105** [comment]
jsonrpc call: map[code:1 message:GetActor called on undefined address]

**Comment by Gui1105** [comment]
> jsonrpc call: map[code:1 message:GetActor called on undefined address]

查询传的是普通地址（f1....）

```

client = filecoin.New("......@filecoin.infura.io")

```

**Comment by myxtype** [comment]
> > jsonrpc call: map[code:1 message:GetActor called on undefined address]
> 
> 查询传的是普通地址（f1....）
> 
> ```
> 
> client = filecoin.New("......@filecoin.infura.io")
> ```

你加我QQ吧：792598794

**Comment by 15365917109** [comment]
@Gui1105 我也遇到了你提的问题，请问当初是如何解决了。求共享
